import React, { useEffect, useRef, useState } from "react";
import { NodeDock } from "../dock/NodeDock";
import { InfrastructureNode, InfrastructureNodeView } from "../nodes/infrastructure/InfrastructureNode";
import { TRAFFIC_SOURCE_ID } from "../../simulation/SimulationEngine";
import { useSimulationStore } from "../../simulation/store";
import { getComponentDefinition } from "../../simulation/componentRegistry";
import type { Connection } from "../../engine/types";

type Point = { x: number; y: number };
type DragState = { type: "pan"; startMouse: Point; startPan: Point } | { type: "node"; nodeId: string; offset: Point } | null;
type WhiteboardProps = { onExit?: () => void };
type FlowDot = { id: number; progress: number };
const MIN_ZOOM=.35, MAX_ZOOM=2, GRID_SIZE=32, REQUEST_RATE=40;
const SOURCE_POSITION={x:360,y:360}, SOURCE_SIZE={width:160,height:90};

export default function Whiteboard({onExit}:WhiteboardProps){
 const boardRef=useRef<HTMLDivElement>(null),dragRef=useRef<DragState>(null);
 const [nodes,setNodes]=useState<InfrastructureNode[]>([]),[connections,setConnections]=useState<Connection[]>([]),[connectingFrom,setConnectingFrom]=useState<string|null>(null),[selectedConnectionId,setSelectedConnectionId]=useState<string|null>(null),[pan,setPan]=useState<Point>({x:0,y:0}),[zoom,setZoom]=useState(1),[draggedNodeId,setDraggedNodeId]=useState<string|null>(null),[dragPosition,setDragPosition]=useState<Point|null>(null),[isPanning,setIsPanning]=useState(false),[flowTime,setFlowTime]=useState(0),[successSince,setSuccessSince]=useState<number|null>(null),[completed,setCompleted]=useState(false);
 const problem=useSimulationStore(s=>s.problem),loadProblem=useSimulationStore(s=>s.loadProblem);
 useEffect(()=>{void loadProblem("url-shortener-v1")},[loadProblem]);
 useEffect(()=>{let f=0,s=performance.now();const a=(n:number)=>{setFlowTime((n-s)/1000);f=requestAnimationFrame(a)};f=requestAnimationFrame(a);return()=>cancelAnimationFrame(f)},[]);
 useEffect(()=>{const k=(e:KeyboardEvent)=>{if((e.key==="Delete"||e.key==="Backspace")&&selectedConnectionId){setConnections(c=>c.filter(x=>x.id!==selectedConnectionId));setSelectedConnectionId(null)}if(e.key==="Escape"){setConnectingFrom(null);setSelectedConnectionId(null)}};window.addEventListener("keydown",k);return()=>window.removeEventListener("keydown",k)},[selectedConnectionId]);
 function screenToWorld(x:number,y:number){const r=boardRef.current?.getBoundingClientRect();return r?{x:(x-r.left-pan.x)/zoom,y:(y-r.top-pan.y)/zoom}:{x:0,y:0}}
 function zoomAt(x:number,y:number,z:number){const r=boardRef.current?.getBoundingClientRect();if(!r)return;const nz=Math.min(MAX_ZOOM,Math.max(MIN_ZOOM,z)),mx=x-r.left,my=y-r.top,wx=(mx-pan.x)/zoom,wy=(my-pan.y)/zoom;setPan({x:mx-wx*nz,y:my-wy*nz});setZoom(nz)}
 function pick(t:InfrastructureNode,e:React.PointerEvent<HTMLDivElement>){const m=screenToWorld(e.clientX,e.clientY),p={x:m.x-t.size.width/2,y:m.y-t.size.height/2},n=new InfrastructureNode(t.componentType,p);setNodes(c=>[...c,n]);setDraggedNodeId(n.id);setDragPosition(p);dragRef.current={type:"node",nodeId:n.id,offset:{x:t.size.width/2,y:t.size.height/2}}}
 function drag(e:React.PointerEvent,n:InfrastructureNode){e.stopPropagation();const m=screenToWorld(e.clientX,e.clientY);setDraggedNodeId(n.id);setDragPosition({...n.position});dragRef.current={type:"node",nodeId:n.id,offset:{x:m.x-n.position.x,y:m.y-n.position.y}}}
 function down(e:React.PointerEvent<HTMLDivElement>){if(e.button!==0)return;setSelectedConnectionId(null);dragRef.current={type:"pan",startMouse:{x:e.clientX,y:e.clientY},startPan:pan};setIsPanning(true);e.currentTarget.setPointerCapture(e.pointerId)}
 function move(e:React.PointerEvent<HTMLDivElement>){const d=dragRef.current;if(!d)return;if(d.type==="pan"){setPan({x:d.startPan.x+e.clientX-d.startMouse.x,y:d.startPan.y+e.clientY-d.startMouse.y});return}const m=screenToWorld(e.clientX,e.clientY);setDragPosition({x:m.x-d.offset.x,y:m.y-d.offset.y})}
 function up(e:React.PointerEvent<HTMLDivElement>){const d=dragRef.current;if(d?.type==="node"&&dragPosition)setNodes(c=>c.map(n=>{if(n.id===d.nodeId)n.moveTo({...dragPosition});return n}));dragRef.current=null;setDraggedNodeId(null);setDragPosition(null);setIsPanning(false);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}
 function startConnection(id:string){setSelectedConnectionId(null);setConnectingFrom(c=>c===id?null:id)}
 function finishConnection(n:InfrastructureNode){if(!connectingFrom||connectingFrom===n.id)return;if(!connections.some(c=>c.sourceId===connectingFrom&&c.targetId===n.id))setConnections(c=>[...c,{id:crypto.randomUUID(),sourceId:connectingFrom,targetId:n.id}]);setConnectingFrom(null)}
 function deleteNode(n:InfrastructureNode){setNodes(c=>c.filter(x=>x.id!==n.id));setConnections(c=>c.filter(x=>x.sourceId!==n.id&&x.targetId!==n.id))}
 function endpoint(id:string,side:"source"|"target"):Point|null{if(id===TRAFFIC_SOURCE_ID)return{x:SOURCE_POSITION.x+SOURCE_SIZE.width,y:SOURCE_POSITION.y+SOURCE_SIZE.height/2};const n=nodes.find(x=>x.id===id);if(!n)return null;const p=id===draggedNodeId&&dragPosition?dragPosition:n.position;return side==="source"?{x:p.x+n.size.width,y:p.y+n.size.height/2}:{x:p.x,y:p.y+n.size.height/2}}
 function curve(a:Point,b:Point,t:number){const c1={x:a.x+70,y:a.y},c2={x:b.x-70,y:b.y},u=1-t;return{x:u*u*u*a.x+3*u*u*t*c1.x+3*u*t*t*c2.x+t*t*t*b.x,y:u*u*u*a.y+3*u*u*t*c1.y+3*u*t*t*c2.y+t*t*t*b.y}}
 const dragged=draggedNodeId?nodes.find(n=>n.id===draggedNodeId):undefined,sourceConnection=connections.find(c=>c.sourceId===TRAFFIC_SOURCE_ID),server=sourceConnection?nodes.find(n=>n.id===sourceConnection.targetId):undefined,capacity=server?getComponentDefinition(server.componentType).capacity:0,processed=server?Math.min(REQUEST_RATE,capacity):0,dropped=REQUEST_RATE-processed,dots:FlowDot[]=Array.from({length:8},(_,id)=>({id,progress:(flowTime*.55+id/8)%1}));
 const requirementsMet=!!server&&processed===REQUEST_RATE&&dropped===0&&!!problem&&getComponentDefinition(server.componentType).monthlyCost<=problem.constraints.max_budget_per_month;
 useEffect(()=>{if(completed)return;if(!requirementsMet){setSuccessSince(null);return}if(successSince===null){setSuccessSince(flowTime);return}if(flowTime-successSince>=3)setCompleted(true)},[requirementsMet,flowTime,successSince,completed]);
 const stableFor=successSince===null?0:Math.min(3,flowTime-successSince);
 return <div ref={boardRef} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} onWheel={e=>{e.preventDefault();zoomAt(e.clientX,e.clientY,zoom*(e.deltaY<0?1.1:.9))}} className={`relative h-screen w-screen touch-none select-none overflow-hidden bg-slate-50 ${isPanning?"cursor-grabbing":"cursor-grab"}`}>
 <div className="pointer-events-none absolute inset-0" style={{backgroundImage:"linear-gradient(#e2e8f0 1px,transparent 1px),linear-gradient(90deg,#e2e8f0 1px,transparent 1px)",backgroundSize:`${GRID_SIZE*zoom}px ${GRID_SIZE*zoom}px`,backgroundPosition:`${pan.x}px ${pan.y}px`}}/>
 <div className="pointer-events-none absolute left-0 top-0 z-10 origin-top-left" style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}><svg className="absolute left-0 top-0 overflow-visible" width="1" height="1">{connections.map(c=>{const a=endpoint(c.sourceId,"source"),b=endpoint(c.targetId,"target");if(!a||!b)return null;const d=`M ${a.x} ${a.y} C ${a.x+70} ${a.y}, ${b.x-70} ${b.y}, ${b.x} ${b.y}`,sel=selectedConnectionId===c.id;return <g key={c.id} className="pointer-events-auto cursor-pointer" onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();setSelectedConnectionId(c.id)}}><path d={d} fill="none" stroke="transparent" strokeWidth="16" pointerEvents="stroke"/><path d={d} fill="none" stroke={sel?"#ef4444":"#94a3b8"} strokeWidth={sel?3:2}/>{c.sourceId===TRAFFIC_SOURCE_ID&&dots.map(x=>{const p=curve(a,b,x.progress);return <circle key={x.id} cx={p.x} cy={p.y} r="5" fill="#22c55e"/>})}</g>})}</svg>
 <div className="pointer-events-auto absolute rounded-2xl border-2 border-emerald-300 bg-emerald-50 shadow-sm" style={{left:SOURCE_POSITION.x,top:SOURCE_POSITION.y,width:SOURCE_SIZE.width,height:SOURCE_SIZE.height}} onPointerDown={e=>e.stopPropagation()}><div className="flex h-full flex-col justify-center px-4"><div className="flex items-center gap-2 text-sm font-semibold text-emerald-900"><span className="h-2.5 w-2.5 animate-pulse rounded-full bg-emerald-500"/>Request Source</div><div className="mt-1 text-xs text-emerald-700">{REQUEST_RATE} requests/s</div></div><button onClick={e=>{e.stopPropagation();startConnection(TRAFFIC_SOURCE_ID)}} className="absolute -right-3 top-1/2 h-7 w-7 -translate-y-1/2 rounded-full border border-emerald-400 bg-white shadow">→</button>{!sourceConnection&&<div className="pointer-events-none absolute left-full top-1/2 ml-4 flex w-40 -translate-y-1/2 gap-5 overflow-hidden">{dots.slice(0,5).map(x=><span key={x.id} className="h-2.5 w-2.5 shrink-0 rounded-full bg-emerald-500" style={{transform:`translateX(${x.progress*120}px)`}}/>)}</div>}</div>
 {nodes.map(n=>n.id===draggedNodeId?null:<InfrastructureNodeView key={n.id} node={n} load={sourceConnection?.targetId===n.id?REQUEST_RATE:0} connecting={connectingFrom===n.id} onPointerDown={e=>drag(e,n)} onStartConnection={()=>startConnection(n.id)} onFinishConnection={finishConnection} onDelete={deleteNode}/>)}</div>
 {problem&&<NodeDock available={problem.components_available} onPickNode={pick}/>} {dragged&&dragPosition&&<div className="pointer-events-none absolute left-0 top-0 z-[100] origin-top-left" style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}><InfrastructureNodeView node={new InfrastructureNode(dragged.componentType,dragPosition)} isDragging pickupScale={.9} load={sourceConnection?.targetId===dragged.id?REQUEST_RATE:0}/></div>}
 <div onPointerDown={e=>e.stopPropagation()} className="absolute left-5 top-5 z-50 w-80 rounded-2xl border bg-white p-4 shadow-lg"><div className="flex justify-between"><div><div className="text-xs font-semibold uppercase tracking-wide text-slate-400">Problem 1</div><div className="mt-1 text-lg font-semibold">{problem?.title??"Loading…"}</div></div>{onExit&&<button onClick={onExit} className="text-xs text-slate-400">Briefing</button>}</div><p className="mt-2 text-xs leading-5 text-slate-500">{problem?.narrative}</p><div className="mt-4 grid grid-cols-3 gap-2"><Metric label="Incoming" value={`${REQUEST_RATE}/s`}/><Metric label="Processed" value={`${processed}/s`}/><Metric label="Dropped" value={`${dropped}/s`}/></div><div className={`mt-3 rounded-lg px-3 py-2 text-xs font-medium ${requirementsMet?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{requirementsMet?`Requirements met · verifying stability ${stableFor.toFixed(1)}/3.0s`:"Connect the request source to a Server with enough capacity."}</div></div>
 {completed&&<div onPointerDown={e=>e.stopPropagation()} className="absolute inset-0 z-[200] grid place-items-center bg-slate-900/25 backdrop-blur-[2px]"><div className="w-[min(420px,calc(100vw-40px))] rounded-3xl bg-white p-7 text-center shadow-2xl"><div className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-emerald-100 text-2xl text-emerald-700">✓</div><h2 className="mt-4 text-2xl font-bold text-slate-900">Problem solved</h2><p className="mt-2 text-sm leading-6 text-slate-500">Your server is processing all {REQUEST_RATE} requests per second with no dropped requests and stays within the problem budget.</p><button onClick={()=>setCompleted(false)} className="mt-6 rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white">Keep exploring</button></div></div>}
 {selectedConnectionId&&<button onPointerDown={e=>e.stopPropagation()} onClick={()=>{setConnections(c=>c.filter(x=>x.id!==selectedConnectionId));setSelectedConnectionId(null)}} className="absolute left-1/2 top-5 z-[70] -translate-x-1/2 rounded-lg bg-red-600 px-3 py-2 text-xs font-semibold text-white shadow">Delete connection</button>}
 <div onPointerDown={e=>e.stopPropagation()} className="absolute bottom-5 right-5 z-50 flex overflow-hidden rounded-xl border bg-white shadow"><button onClick={()=>zoomAt(innerWidth/2,innerHeight/2,zoom-.1)} className="h-10 w-10">−</button><button onClick={()=>{setZoom(1);setPan({x:0,y:0})}} className="border-x px-3 text-xs">{Math.round(zoom*100)}%</button><button onClick={()=>zoomAt(innerWidth/2,innerHeight/2,zoom+.1)} className="h-10 w-10">+</button></div></div>
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-2 text-center"><div className="text-xs font-semibold text-slate-900">{value}</div><div className="mt-.5 text-[10px] text-slate-400">{label}</div></div>}
